//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunMoonCalendar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SunMoonCalendar.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical twilight ({0:HH:mm} - {1:HH:mm})|As in astronomical twilight.
        /// </summary>
        internal static string msgAstronomicalTwilight {
            get {
                return ResourceManager.GetString("msgAstronomicalTwilight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun and moon calendar [{0} / {1}, Location: {2}]|As in the main window&apos;s caption with current selected month and current location name.
        /// </summary>
        internal static string msgCaptionText {
            get {
                return ResourceManager.GetString("msgCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil twilight ({0:HH:mm} - {1:HH:mm})|As in civil twilight.
        /// </summary>
        internal static string msgCivilTwilight {
            get {
                return ResourceManager.GetString("msgCivilTwilight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E|As in a letter for the east compass point.
        /// </summary>
        internal static string msgCompassPointEastShort {
            get {
                return ResourceManager.GetString("msgCompassPointEastShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE|As in a letters for the north-east compass point.
        /// </summary>
        internal static string msgCompassPointNorthEastShort {
            get {
                return ResourceManager.GetString("msgCompassPointNorthEastShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N|As in a letter for the north compass point.
        /// </summary>
        internal static string msgCompassPointNorthShort {
            get {
                return ResourceManager.GetString("msgCompassPointNorthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW|As in a letters for the north-west compass point.
        /// </summary>
        internal static string msgCompassPointNorthWestShort {
            get {
                return ResourceManager.GetString("msgCompassPointNorthWestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE|As in a letters for the south-east compass point.
        /// </summary>
        internal static string msgCompassPointSouthEastShort {
            get {
                return ResourceManager.GetString("msgCompassPointSouthEastShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S|As in a letter for the south compass point.
        /// </summary>
        internal static string msgCompassPointSouthShort {
            get {
                return ResourceManager.GetString("msgCompassPointSouthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW|As in a letters for the south-west compass point.
        /// </summary>
        internal static string msgCompassPointSouthWestShort {
            get {
                return ResourceManager.GetString("msgCompassPointSouthWestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W|As in a letter for the west compass point.
        /// </summary>
        internal static string msgCompassPointWestShort {
            get {
                return ResourceManager.GetString("msgCompassPointWestShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Quarter|As in first quarter (moon).
        /// </summary>
        internal static string msgMoonFirstQuarter {
            get {
                return ResourceManager.GetString("msgMoonFirstQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Moon|As in full moon.
        /// </summary>
        internal static string msgMoonFullMoon {
            get {
                return ResourceManager.GetString("msgMoonFullMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quarter|As in last quarter (moon).
        /// </summary>
        internal static string msgMoonLastQuarter {
            get {
                return ResourceManager.GetString("msgMoonLastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New moon|As in new moon.
        /// </summary>
        internal static string msgMoonNewMoon {
            get {
                return ResourceManager.GetString("msgMoonNewMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning Crescent|As in waning crescent (moon).
        /// </summary>
        internal static string msgMoonWaningCrescent {
            get {
                return ResourceManager.GetString("msgMoonWaningCrescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waning Gibbous|As in waning gibbous (moon).
        /// </summary>
        internal static string msgMoonWaningGibbous {
            get {
                return ResourceManager.GetString("msgMoonWaningGibbous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing Crescent|As in waxing crescent (moon).
        /// </summary>
        internal static string msgMoonWaxingCrescent {
            get {
                return ResourceManager.GetString("msgMoonWaxingCrescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waxing Gibbous|As in waxing gibbous (moon).
        /// </summary>
        internal static string msgMoonWaxingGibbous {
            get {
                return ResourceManager.GetString("msgMoonWaxingGibbous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical twilight ({0:HH:mm} - {1:HH:mm})|As in nautical twilight.
        /// </summary>
        internal static string msgNauticalTwilight {
            get {
                return ResourceManager.GetString("msgNauticalTwilight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not rise|as in the sun/moon doesn&apos;t rise.
        /// </summary>
        internal static string msgObjectNoRise {
            get {
                return ResourceManager.GetString("msgObjectNoRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not set|as in the sun/moon doesn&apos;t set.
        /// </summary>
        internal static string msgObjectNoSet {
            get {
                return ResourceManager.GetString("msgObjectNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N: {0}{1}A: {2:F2}°{3}L: {4}:{5} h|N as in Noon and A as in angle and L as in day length, h as in hours.
        /// </summary>
        internal static string msgSunInfoShort {
            get {
                return ResourceManager.GetString("msgSunInfoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day ({0:HH:mm} - {1:HH:mm})|Day as in not actually a twilight.
        /// </summary>
        internal static string msgTwilightDay {
            get {
                return ResourceManager.GetString("msgTwilightDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night ({0:HH:mm} - {1:HH:mm})|Night as in not actually a twilight.
        /// </summary>
        internal static string msgTwilightNight {
            get {
                return ResourceManager.GetString("msgTwilightNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None|None as in not actually a twilight.
        /// </summary>
        internal static string msgTwilightNone {
            get {
                return ResourceManager.GetString("msgTwilightNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time, Moon (UTC {0} {1:F0})|A text describing a local time with UTC offset of the moon.
        /// </summary>
        internal static string msgUTCMoon {
            get {
                return ResourceManager.GetString("msgUTCMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time, Sun (UTC {0} {1:F0})|A text describing a local time with UTC offset of the sun.
        /// </summary>
        internal static string msgUTCSun {
            get {
                return ResourceManager.GetString("msgUTCSun", resourceCulture);
            }
        }
    }
}
